<template>
    <div>
        <Modal v-model="iconSelector" title="ICON сонгох" width="1000px">

            <div style="text-align:center">
                <Input :placeholder="lang.search" v-model="iconSearch"/>
                <section class="icons-list">
                    <div class="pagewidth">

                        <div class="icon-section" v-for="iconGroup in filteredIcons" :key="iconGroup.index">
                            <h3>{{ iconGroup.title }}</h3>
                            <div class="icon-container" v-for="svg in iconGroup.svgs" :key="svg.index" v-if="iconGroup.hasOwnProperty('svgs')"
                                 @click="setIcon(svg)">
                                <img :url="svg"></img><span class="icon-name"> {{ svg }}</span>
                            </div>
                            <div class="icon-container" v-for="icon in iconGroup.icons" :key="icon.index"
                                 @click="setIcon(icon)">
                                <i :class="icon"></i><span class="icon-name"> {{ icon }}</span>
                            </div>
                        </div>

                    </div>
                    <!-- /pagewidth -->
                </section>
            </div>
            <div slot="footer">
            </div>
        </Modal>
    </div>
</template>

<script>
export default {
    props:[
        "iconSelector"
    ],
    data() {
        return {
            iconSearch: "",
            iconData: [
                {"svgs":["/assets/icons/duotone/Brassiere.svg","/assets/icons/duotone/Briefcase.svg","/assets/icons/duotone/Cap.svg","/assets/icons/duotone/Crown.svg","/assets/icons/duotone/Dress.svg","/assets/icons/duotone/Hanger.svg","/assets/icons/duotone/Hat.svg","/assets/icons/duotone/Panties.svg","/assets/icons/duotone/Shirt.svg","/assets/icons/duotone/Shoes.svg","/assets/icons/duotone/Shorts.svg","/assets/icons/duotone/Sneakers.svg","/assets/icons/duotone/Socks.svg","/assets/icons/duotone/Sun-glasses.svg","/assets/icons/duotone/T-Shirt.svg","/assets/icons/duotone/Tie.svg"],"title":"SVG Duotone Clothes"},{"svgs":["/assets/icons/duotone/Backspace.svg","/assets/icons/duotone/CMD.svg","/assets/icons/duotone/Code.svg","/assets/icons/duotone/Commit.svg","/assets/icons/duotone/Compiling.svg","/assets/icons/duotone/Control.svg","/assets/icons/duotone/Done-circle.svg","/assets/icons/duotone/Error-circle.svg","/assets/icons/duotone/Git1.svg","/assets/icons/duotone/Git2.svg","/assets/icons/duotone/Git3.svg","/assets/icons/duotone/Git4.svg","/assets/icons/duotone/Github.svg","/assets/icons/duotone/Info-circle.svg","/assets/icons/duotone/Left-circle.svg","/assets/icons/duotone/Loading.svg","/assets/icons/duotone/Lock-circle.svg","/assets/icons/duotone/Lock-overturning.svg","/assets/icons/duotone/Minus.svg","/assets/icons/duotone/Option.svg","/assets/icons/duotone/Plus.svg","/assets/icons/duotone/Puzzle.svg","/assets/icons/duotone/Question-circle.svg","/assets/icons/duotone/Right-circle.svg","/assets/icons/duotone/Settings4.svg","/assets/icons/duotone/Shift.svg","/assets/icons/duotone/Spy.svg","/assets/icons/duotone/Stop.svg","/assets/icons/duotone/Terminal.svg","/assets/icons/duotone/Thunder-circle.svg","/assets/icons/duotone/Time-schedule.svg","/assets/icons/duotone/Warning-1-circle.svg","/assets/icons/duotone/Warning-2.svg"],"title":"SVG Duotone Code"},{"svgs":["/assets/icons/duotone/Active-call.svg","/assets/icons/duotone/Add-user.svg","/assets/icons/duotone/Address-card.svg","/assets/icons/duotone/Adress-book1.svg","/assets/icons/duotone/Adress-book2.svg","/assets/icons/duotone/Archive.svg","/assets/icons/duotone/Call-1.svg","/assets/icons/duotone/Call.svg","/assets/icons/duotone/Chat-check.svg","/assets/icons/duotone/Chat-error.svg","/assets/icons/duotone/Chat-locked.svg","/assets/icons/duotone/Chat-smile.svg","/assets/icons/duotone/Chat.svg","/assets/icons/duotone/Chat1.svg","/assets/icons/duotone/Chat2.svg","/assets/icons/duotone/Chat4.svg","/assets/icons/duotone/Chat5.svg","/assets/icons/duotone/Chat6.svg","/assets/icons/duotone/Clipboard-check.svg","/assets/icons/duotone/Clipboard-list.svg","/assets/icons/duotone/Contact1.svg","/assets/icons/duotone/Delete-user.svg","/assets/icons/duotone/Dial-numbers.svg","/assets/icons/duotone/Flag.svg","/assets/icons/duotone/Forward.svg","/assets/icons/duotone/Group-chat.svg","/assets/icons/duotone/Group.svg","/assets/icons/duotone/Incoming-box.svg","/assets/icons/duotone/Incoming-call.svg","/assets/icons/duotone/Incoming-mail.svg","/assets/icons/duotone/Mail-at.svg","/assets/icons/duotone/Mail-attachment.svg","/assets/icons/duotone/Mail-box.svg","/assets/icons/duotone/Mail-error.svg","/assets/icons/duotone/Mail-heart.svg","/assets/icons/duotone/Mail-locked.svg","/assets/icons/duotone/Mail-notification.svg","/assets/icons/duotone/Mail-opened.svg","/assets/icons/duotone/Mail-unocked.svg","/assets/icons/duotone/Mail.svg","/assets/icons/duotone/Missed-call.svg","/assets/icons/duotone/More.svg","/assets/icons/duotone/Outgoing-box.svg","/assets/icons/duotone/Outgoing-call.svg","/assets/icons/duotone/Outgoing-mail.svg","/assets/icons/duotone/RSS.svg","/assets/icons/duotone/Readed-mail.svg","/assets/icons/duotone/Reply-all.svg","/assets/icons/duotone/Reply.svg","/assets/icons/duotone/Right.svg","/assets/icons/duotone/Safe-chat.svg","/assets/icons/duotone/Send.svg","/assets/icons/duotone/Sending mail.svg","/assets/icons/duotone/Sending.svg","/assets/icons/duotone/Share.svg","/assets/icons/duotone/Shield-thunder.svg","/assets/icons/duotone/Shield-user.svg","/assets/icons/duotone/Snoozed-mail.svg","/assets/icons/duotone/Spam.svg","/assets/icons/duotone/Thumbtack.svg","/assets/icons/duotone/Urgent-mail.svg","/assets/icons/duotone/Write.svg"],"title":"SVG Duotone Communication"},{"svgs":["/assets/icons/duotone/Baking-glove.svg","/assets/icons/duotone/Bowl.svg","/assets/icons/duotone/Chef.svg","/assets/icons/duotone/Cooking-book.svg","/assets/icons/duotone/Cooking-pot.svg","/assets/icons/duotone/Cutting board.svg","/assets/icons/duotone/Dinner.svg","/assets/icons/duotone/Dish.svg","/assets/icons/duotone/Dishes.svg","/assets/icons/duotone/Fork-spoon-knife.svg","/assets/icons/duotone/Fork-spoon.svg","/assets/icons/duotone/Fork.svg","/assets/icons/duotone/Frying-pan.svg","/assets/icons/duotone/Grater.svg","/assets/icons/duotone/Kitchen-scale.svg","/assets/icons/duotone/Knife1.svg","/assets/icons/duotone/Knife2.svg","/assets/icons/duotone/KnifeAndFork1.svg","/assets/icons/duotone/KnifeAndFork2.svg","/assets/icons/duotone/Ladle.svg","/assets/icons/duotone/Rolling-pin.svg","/assets/icons/duotone/Saucepan.svg","/assets/icons/duotone/Shovel.svg","/assets/icons/duotone/Sieve.svg","/assets/icons/duotone/Spoon.svg"],"title":"SVG Duotone Cooking"},{"svgs":["/assets/icons/duotone/Adjust.svg","/assets/icons/duotone/Anchor-center-down.svg","/assets/icons/duotone/Anchor-center-up.svg","/assets/icons/duotone/Anchor-center.svg","/assets/icons/duotone/Anchor-left-down.svg","/assets/icons/duotone/Anchor-left-up.svg","/assets/icons/duotone/Anchor-left.svg","/assets/icons/duotone/Anchor-right-down.svg","/assets/icons/duotone/Anchor-right-up.svg","/assets/icons/duotone/Anchor-right.svg","/assets/icons/duotone/Arrows.svg","/assets/icons/duotone/Bezier-curve.svg","/assets/icons/duotone/Border.svg","/assets/icons/duotone/Brush.svg","/assets/icons/duotone/Bucket.svg","/assets/icons/duotone/Cap-1.svg","/assets/icons/duotone/Cap-2.svg","/assets/icons/duotone/Cap-3.svg","/assets/icons/duotone/Circle.svg","/assets/icons/duotone/Color-profile.svg","/assets/icons/duotone/Color.svg","/assets/icons/duotone/Component.svg","/assets/icons/duotone/Crop.svg","/assets/icons/duotone/Difference.svg","/assets/icons/duotone/Edit.svg","/assets/icons/duotone/Eraser.svg","/assets/icons/duotone/Flatten.svg","/assets/icons/duotone/Flip-horizontal.svg","/assets/icons/duotone/Flip-vertical.svg","/assets/icons/duotone/Horizontal.svg","/assets/icons/duotone/Image.svg","/assets/icons/duotone/Interselect.svg","/assets/icons/duotone/Join-1.svg","/assets/icons/duotone/Join-2.svg","/assets/icons/duotone/Join-3.svg","/assets/icons/duotone/Layers.svg","/assets/icons/duotone/Line.svg","/assets/icons/duotone/Magic.svg","/assets/icons/duotone/Mask.svg","/assets/icons/duotone/Patch.svg","/assets/icons/duotone/Pen-tool-vector.svg","/assets/icons/duotone/PenAndRuller.svg","/assets/icons/duotone/Pencil.svg","/assets/icons/duotone/Picker.svg","/assets/icons/duotone/Pixels.svg","/assets/icons/duotone/Polygon.svg","/assets/icons/duotone/Position.svg","/assets/icons/duotone/Rectangle.svg","/assets/icons/duotone/Saturation.svg","/assets/icons/duotone/Select.svg","/assets/icons/duotone/Sketch.svg","/assets/icons/duotone/Stamp.svg","/assets/icons/duotone/Substract.svg","/assets/icons/duotone/Target.svg","/assets/icons/duotone/Triangle.svg","/assets/icons/duotone/Union.svg","/assets/icons/duotone/Verified.svg","/assets/icons/duotone/Vertical.svg","/assets/icons/duotone/ZoomMinus.svg","/assets/icons/duotone/ZoomPlus.svg"],"title":"SVG Duotone Design"},{"svgs":["/assets/icons/duotone/Airpods.svg","/assets/icons/duotone/Android.svg","/assets/icons/duotone/Apple-Watch.svg","/assets/icons/duotone/Battery-charging.svg","/assets/icons/duotone/Battery-empty.svg","/assets/icons/duotone/Battery-full.svg","/assets/icons/duotone/Battery-half.svg","/assets/icons/duotone/Bluetooth.svg","/assets/icons/duotone/CPU1.svg","/assets/icons/duotone/CPU2.svg","/assets/icons/duotone/Camera.svg","/assets/icons/duotone/Cardboard-vr.svg","/assets/icons/duotone/Cassete.svg","/assets/icons/duotone/Diagnostics.svg","/assets/icons/duotone/Display1.svg","/assets/icons/duotone/Display2.svg","/assets/icons/duotone/Display3.svg","/assets/icons/duotone/Gameboy.svg","/assets/icons/duotone/Gamepad1.svg","/assets/icons/duotone/Gamepad2.svg","/assets/icons/duotone/Generator.svg","/assets/icons/duotone/Hard-drive.svg","/assets/icons/duotone/Headphones.svg","/assets/icons/duotone/Homepod.svg","/assets/icons/duotone/Keyboard.svg","/assets/icons/duotone/LTE1.svg","/assets/icons/duotone/LTE2.svg","/assets/icons/duotone/Laptop-macbook.svg","/assets/icons/duotone/Laptop.svg","/assets/icons/duotone/Mic.svg","/assets/icons/duotone/Midi.svg","/assets/icons/duotone/Mouse.svg","/assets/icons/duotone/Phone.svg","/assets/icons/duotone/Printer.svg","/assets/icons/duotone/Radio.svg","/assets/icons/duotone/Router1.svg","/assets/icons/duotone/Router2.svg","/assets/icons/duotone/SD-card.svg","/assets/icons/duotone/Server.svg","/assets/icons/duotone/Speaker.svg","/assets/icons/duotone/TV1.svg","/assets/icons/duotone/TV2.svg","/assets/icons/duotone/Tablet.svg","/assets/icons/duotone/USB.svg","/assets/icons/duotone/Usb-storage.svg","/assets/icons/duotone/Video-camera.svg","/assets/icons/duotone/Watch1.svg","/assets/icons/duotone/Watch2.svg","/assets/icons/duotone/Wi-fi.svg","/assets/icons/duotone/iMac.svg","/assets/icons/duotone/iPhone-X.svg","/assets/icons/duotone/iPhone-back.svg","/assets/icons/duotone/iPhone-x-back.svg"],"title":"SVG Duotone Devices"},{"svgs":["/assets/icons/duotone/Air-conditioning.svg","/assets/icons/duotone/Blender.svg","/assets/icons/duotone/Fan.svg","/assets/icons/duotone/Fridge.svg","/assets/icons/duotone/Gas-stove.svg","/assets/icons/duotone/Highvoltage.svg","/assets/icons/duotone/Iron.svg","/assets/icons/duotone/Kettle.svg","/assets/icons/duotone/Mixer.svg","/assets/icons/duotone/Outlet.svg","/assets/icons/duotone/Range-hood.svg","/assets/icons/duotone/Shutdown.svg","/assets/icons/duotone/Socket-eu.svg","/assets/icons/duotone/Socket-us.svg","/assets/icons/duotone/Washer.svg","/assets/icons/duotone/air-dryer.svg"],"title":"SVG Duotone Electric"},{"svgs":["/assets/icons/duotone/Cloud-download.svg","/assets/icons/duotone/Cloud-upload.svg","/assets/icons/duotone/Compilation.svg","/assets/icons/duotone/Compiled-file.svg","/assets/icons/duotone/Deleted-file.svg","/assets/icons/duotone/Deleted-folder.svg","/assets/icons/duotone/Download.svg","/assets/icons/duotone/DownloadedFile.svg","/assets/icons/duotone/Downloads-folder.svg","/assets/icons/duotone/Export.svg","/assets/icons/duotone/File-Minus.svg","/assets/icons/duotone/File-Plus.svg","/assets/icons/duotone/File-cloud.svg","/assets/icons/duotone/File-done.svg","/assets/icons/duotone/File.svg","/assets/icons/duotone/Folder-check.svg","/assets/icons/duotone/Folder-cloud.svg","/assets/icons/duotone/Folder-error.svg","/assets/icons/duotone/Folder-heart.svg","/assets/icons/duotone/Folder-minus.svg","/assets/icons/duotone/Folder-plus.svg","/assets/icons/duotone/Folder-solid.svg","/assets/icons/duotone/Folder-star.svg","/assets/icons/duotone/Folder-thunder.svg","/assets/icons/duotone/Folder.svg","/assets/icons/duotone/Group-folders.svg","/assets/icons/duotone/Import.svg","/assets/icons/duotone/Locked-folder.svg","/assets/icons/duotone/Media-folder.svg","/assets/icons/duotone/Media.svg","/assets/icons/duotone/Music.svg","/assets/icons/duotone/Pictures1.svg","/assets/icons/duotone/Pictures2.svg","/assets/icons/duotone/Protected-file.svg","/assets/icons/duotone/Selected-file.svg","/assets/icons/duotone/Upload-folder.svg","/assets/icons/duotone/Upload.svg","/assets/icons/duotone/Uploaded-file.svg","/assets/icons/duotone/User-folder.svg"],"title":"SVG Duotone Files"},{"svgs":["/assets/icons/duotone/Beer.svg","/assets/icons/duotone/Bottle1.svg","/assets/icons/duotone/Bottle2.svg","/assets/icons/duotone/Bread.svg","/assets/icons/duotone/Bucket.svg","/assets/icons/duotone/Burger.svg","/assets/icons/duotone/Cake.svg","/assets/icons/duotone/Carrot.svg","/assets/icons/duotone/Cheese.svg","/assets/icons/duotone/Chicken.svg","/assets/icons/duotone/Coffee1.svg","/assets/icons/duotone/Coffee2.svg","/assets/icons/duotone/Cookie.svg","/assets/icons/duotone/Dinner.svg","/assets/icons/duotone/Fish.svg","/assets/icons/duotone/French Bread.svg","/assets/icons/duotone/Glass-martini.svg","/assets/icons/duotone/Ice-cream1.svg","/assets/icons/duotone/Ice-cream2.svg","/assets/icons/duotone/Miso-soup.svg","/assets/icons/duotone/Orange.svg","/assets/icons/duotone/Pizza.svg","/assets/icons/duotone/Sushi.svg","/assets/icons/duotone/Two-bottles.svg","/assets/icons/duotone/Wine.svg"],"title":"SVG Duotone Food"},{"svgs":["/assets/icons/duotone/Attachment1.svg","/assets/icons/duotone/Attachment2.svg","/assets/icons/duotone/Bank.svg","/assets/icons/duotone/Binocular.svg","/assets/icons/duotone/Bookmark.svg","/assets/icons/duotone/Clip.svg","/assets/icons/duotone/Clipboard.svg","/assets/icons/duotone/Copy.svg","/assets/icons/duotone/Cursor.svg","/assets/icons/duotone/Dislike.svg","/assets/icons/duotone/Duplicate.svg","/assets/icons/duotone/Edit.svg","/assets/icons/duotone/Expand-arrows.svg","/assets/icons/duotone/Fire.svg","/assets/icons/duotone/Folder.svg","/assets/icons/duotone/Half-heart.svg","/assets/icons/duotone/Half-star.svg","/assets/icons/duotone/Heart.svg","/assets/icons/duotone/Hidden.svg","/assets/icons/duotone/Like.svg","/assets/icons/duotone/Lock.svg","/assets/icons/duotone/Notification2.svg","/assets/icons/duotone/Notifications1.svg","/assets/icons/duotone/Other1.svg","/assets/icons/duotone/Other2.svg","/assets/icons/duotone/Sad.svg","/assets/icons/duotone/Save.svg","/assets/icons/duotone/Scale.svg","/assets/icons/duotone/Scissors.svg","/assets/icons/duotone/Search.svg","/assets/icons/duotone/Settings-1.svg","/assets/icons/duotone/Settings-2.svg","/assets/icons/duotone/Settings-3.svg","/assets/icons/duotone/Shield-check.svg","/assets/icons/duotone/Shield-disabled.svg","/assets/icons/duotone/Shield-protected.svg","/assets/icons/duotone/Size.svg","/assets/icons/duotone/Smile.svg","/assets/icons/duotone/Star.svg","/assets/icons/duotone/Thunder-move.svg","/assets/icons/duotone/Thunder.svg","/assets/icons/duotone/Trash.svg","/assets/icons/duotone/Unlock.svg","/assets/icons/duotone/Update.svg","/assets/icons/duotone/User.svg","/assets/icons/duotone/Visible.svg"],"title":"SVG Duotone General"},{"svgs":["/assets/icons/duotone/Air-ballon.svg","/assets/icons/duotone/Alarm-clock.svg","/assets/icons/duotone/Armchair.svg","/assets/icons/duotone/Bag-chair.svg","/assets/icons/duotone/Bath.svg","/assets/icons/duotone/Bed.svg","/assets/icons/duotone/Book-open.svg","/assets/icons/duotone/Book.svg","/assets/icons/duotone/Box.svg","/assets/icons/duotone/Broom.svg","/assets/icons/duotone/Building.svg","/assets/icons/duotone/Bulb1.svg","/assets/icons/duotone/Bulb2.svg","/assets/icons/duotone/Chair1.svg","/assets/icons/duotone/Chair2.svg","/assets/icons/duotone/Clock.svg","/assets/icons/duotone/Commode1.svg","/assets/icons/duotone/Commode2.svg","/assets/icons/duotone/Couch.svg","/assets/icons/duotone/Cupboard.svg","/assets/icons/duotone/Curtains.svg","/assets/icons/duotone/Deer.svg","/assets/icons/duotone/Door-open.svg","/assets/icons/duotone/Earth.svg","/assets/icons/duotone/Fireplace.svg","/assets/icons/duotone/Flashlight.svg","/assets/icons/duotone/Flower1.svg","/assets/icons/duotone/Flower2.svg","/assets/icons/duotone/Flower3.svg","/assets/icons/duotone/Globe.svg","/assets/icons/duotone/Home-heart.svg","/assets/icons/duotone/Home.svg","/assets/icons/duotone/Home2.svg","/assets/icons/duotone/Key.svg","/assets/icons/duotone/Ladder.svg","/assets/icons/duotone/Lamp1.svg","/assets/icons/duotone/Lamp2.svg","/assets/icons/duotone/Library.svg","/assets/icons/duotone/Mailbox.svg","/assets/icons/duotone/Mirror.svg","/assets/icons/duotone/Picture.svg","/assets/icons/duotone/Ruller.svg","/assets/icons/duotone/Stairs.svg","/assets/icons/duotone/Timer.svg","/assets/icons/duotone/Toilet.svg","/assets/icons/duotone/Towel.svg","/assets/icons/duotone/Trash.svg","/assets/icons/duotone/Water-mixer.svg","/assets/icons/duotone/Weight1.svg","/assets/icons/duotone/Weight2.svg","/assets/icons/duotone/Wood-horse.svg","/assets/icons/duotone/Wood1.svg","/assets/icons/duotone/Wood2.svg"],"title":"SVG Duotone Home"},{"svgs":["/assets/icons/duotone/Bank.svg","/assets/icons/duotone/Briefcase.svg","/assets/icons/duotone/Calendar.svg","/assets/icons/duotone/Close-Square.svg","/assets/icons/duotone/Cog.svg","/assets/icons/duotone/Comment.svg","/assets/icons/duotone/Doughnut.svg","/assets/icons/duotone/Edit.svg","/assets/icons/duotone/Envelope.svg","/assets/icons/duotone/File-Plus.svg","/assets/icons/duotone/File-Search.svg","/assets/icons/duotone/File-Upload.svg","/assets/icons/duotone/File.svg","/assets/icons/duotone/Folder.svg","/assets/icons/duotone/Grid-Horizontal.svg","/assets/icons/duotone/Grid-Vetical.svg","/assets/icons/duotone/Grid.svg","/assets/icons/duotone/Image.svg","/assets/icons/duotone/Insert.svg","/assets/icons/duotone/Line-03-Down.svg","/assets/icons/duotone/Line-03-Up.svg","/assets/icons/duotone/Lock.svg","/assets/icons/duotone/Map-Marker.svg","/assets/icons/duotone/Minus-Square.svg","/assets/icons/duotone/Monitor.svg","/assets/icons/duotone/Options-Square.svg","/assets/icons/duotone/Phone.svg","/assets/icons/duotone/Pie-04.svg","/assets/icons/duotone/Plus-Square.svg","/assets/icons/duotone/Scatter-Up.svg","/assets/icons/duotone/Settings-02.svg","/assets/icons/duotone/Sign-Out.svg","/assets/icons/duotone/Stacked-Area-Down.svg","/assets/icons/duotone/User.svg"],"title":"SVG Duotone Interface"},{"svgs":["/assets/icons/duotone/Layout-3d.svg","/assets/icons/duotone/Layout-4-blocks-2.svg","/assets/icons/duotone/Layout-4-blocks.svg","/assets/icons/duotone/Layout-arrange.svg","/assets/icons/duotone/Layout-grid.svg","/assets/icons/duotone/Layout-horizontal.svg","/assets/icons/duotone/Layout-left-panel-1.svg","/assets/icons/duotone/Layout-left-panel-2.svg","/assets/icons/duotone/Layout-octagon.svg","/assets/icons/duotone/Layout-polygon.svg","/assets/icons/duotone/Layout-right-panel-1.svg","/assets/icons/duotone/Layout-right-panel-2.svg","/assets/icons/duotone/Layout-top-panel-1.svg","/assets/icons/duotone/Layout-top-panel-2.svg","/assets/icons/duotone/Layout-top-panel-3.svg","/assets/icons/duotone/Layout-top-panel-4.svg","/assets/icons/duotone/Layout-top-panel-5.svg","/assets/icons/duotone/Layout-top-panel-6.svg","/assets/icons/duotone/Layout-vertical.svg"],"title":"SVG Duotone Layout"},{"svgs":["/assets/icons/duotone/Compass.svg","/assets/icons/duotone/Direction1.svg","/assets/icons/duotone/Direction2.svg","/assets/icons/duotone/Location-arrow.svg","/assets/icons/duotone/Marker1.svg","/assets/icons/duotone/Marker2.svg","/assets/icons/duotone/Position.svg"],"title":"SVG Duotone Map"},{"svgs":["/assets/icons/duotone/Add-music.svg","/assets/icons/duotone/AirPlay.svg","/assets/icons/duotone/Airplay-video.svg","/assets/icons/duotone/Back.svg","/assets/icons/duotone/Backward.svg","/assets/icons/duotone/CD.svg","/assets/icons/duotone/DVD.svg","/assets/icons/duotone/Eject.svg","/assets/icons/duotone/Equalizer.svg","/assets/icons/duotone/Forward.svg","/assets/icons/duotone/Media-library1.svg","/assets/icons/duotone/Media-library2.svg","/assets/icons/duotone/Media-library3.svg","/assets/icons/duotone/Movie-Lane2.svg","/assets/icons/duotone/Movie-lane1.svg","/assets/icons/duotone/Music-cloud.svg","/assets/icons/duotone/Music-note.svg","/assets/icons/duotone/Music.svg","/assets/icons/duotone/Mute.svg","/assets/icons/duotone/Next.svg","/assets/icons/duotone/Pause.svg","/assets/icons/duotone/Play.svg","/assets/icons/duotone/Playlist1.svg","/assets/icons/duotone/Playlist2.svg","/assets/icons/duotone/Rec.svg","/assets/icons/duotone/Repeat-one.svg","/assets/icons/duotone/Repeat.svg","/assets/icons/duotone/Shuffle.svg","/assets/icons/duotone/Volume-Down.svg","/assets/icons/duotone/Volume-Up.svg","/assets/icons/duotone/Volume-full.svg","/assets/icons/duotone/Volume-half.svg","/assets/icons/duotone/Vynil.svg","/assets/icons/duotone/Youtube.svg"],"title":"SVG Duotone Media"},{"svgs":["/assets/icons/duotone/Angle-double-down.svg","/assets/icons/duotone/Angle-double-left.svg","/assets/icons/duotone/Angle-double-right.svg","/assets/icons/duotone/Angle-double-up.svg","/assets/icons/duotone/Angle-down.svg","/assets/icons/duotone/Angle-left.svg","/assets/icons/duotone/Angle-right.svg","/assets/icons/duotone/Angle-up.svg","/assets/icons/duotone/Arrow-down.svg","/assets/icons/duotone/Arrow-from-bottom.svg","/assets/icons/duotone/Arrow-from-left.svg","/assets/icons/duotone/Arrow-from-right.svg","/assets/icons/duotone/Arrow-from-top.svg","/assets/icons/duotone/Arrow-left.svg","/assets/icons/duotone/Arrow-right.svg","/assets/icons/duotone/Arrow-to-bottom.svg","/assets/icons/duotone/Arrow-to-left.svg","/assets/icons/duotone/Arrow-to-right.svg","/assets/icons/duotone/Arrow-to-up.svg","/assets/icons/duotone/Arrow-up.svg","/assets/icons/duotone/Arrows-h.svg","/assets/icons/duotone/Arrows-v.svg","/assets/icons/duotone/Check.svg","/assets/icons/duotone/Close.svg","/assets/icons/duotone/Double-check.svg","/assets/icons/duotone/Down-2.svg","/assets/icons/duotone/Down-left.svg","/assets/icons/duotone/Down-right.svg","/assets/icons/duotone/Exchange.svg","/assets/icons/duotone/Left-2.svg","/assets/icons/duotone/Left-3.svg","/assets/icons/duotone/Minus.svg","/assets/icons/duotone/Plus.svg","/assets/icons/duotone/Right 3.svg","/assets/icons/duotone/Right-2.svg","/assets/icons/duotone/Route.svg","/assets/icons/duotone/Sign-in.svg","/assets/icons/duotone/Sign-out.svg","/assets/icons/duotone/Up-2.svg","/assets/icons/duotone/Up-down.svg","/assets/icons/duotone/Up-left.svg","/assets/icons/duotone/Up-right.svg","/assets/icons/duotone/Waiting.svg"],"title":"SVG Duotone Navigation"},{"svgs":["/assets/icons/duotone/ATM.svg","/assets/icons/duotone/Bag1.svg","/assets/icons/duotone/Bag2.svg","/assets/icons/duotone/Barcode-read.svg","/assets/icons/duotone/Barcode-scan.svg","/assets/icons/duotone/Barcode.svg","/assets/icons/duotone/Bitcoin.svg","/assets/icons/duotone/Box1.svg","/assets/icons/duotone/Box2.svg","/assets/icons/duotone/Box3.svg","/assets/icons/duotone/Calculator.svg","/assets/icons/duotone/Cart1.svg","/assets/icons/duotone/Cart2.svg","/assets/icons/duotone/Cart3.svg","/assets/icons/duotone/Cart4.svg","/assets/icons/duotone/Cart5.svg","/assets/icons/duotone/Cart6.svg","/assets/icons/duotone/Chart-bar1.svg","/assets/icons/duotone/Chart-bar2.svg","/assets/icons/duotone/Chart-bar3.svg","/assets/icons/duotone/Chart-line1.svg","/assets/icons/duotone/Chart-line2.svg","/assets/icons/duotone/Chart-pie.svg","/assets/icons/duotone/Chart.svg","/assets/icons/duotone/Credit-card.svg","/assets/icons/duotone/Dollar.svg","/assets/icons/duotone/Euro.svg","/assets/icons/duotone/Gift.svg","/assets/icons/duotone/Loader.svg","/assets/icons/duotone/MC.svg","/assets/icons/duotone/Money.svg","/assets/icons/duotone/Pound.svg","/assets/icons/duotone/Price1.svg","/assets/icons/duotone/Price2.svg","/assets/icons/duotone/Rouble.svg","/assets/icons/duotone/Safe.svg","/assets/icons/duotone/Sale1.svg","/assets/icons/duotone/Sale2.svg","/assets/icons/duotone/Settings.svg","/assets/icons/duotone/Sort1.svg","/assets/icons/duotone/Sort2.svg","/assets/icons/duotone/Sort3.svg","/assets/icons/duotone/Ticket.svg","/assets/icons/duotone/Wallet.svg","/assets/icons/duotone/Wallet2.svg","/assets/icons/duotone/Wallet3.svg"],"title":"SVG Duotone Shopping"},{"svgs":["/assets/icons/duotone/Align-auto.svg","/assets/icons/duotone/Align-center.svg","/assets/icons/duotone/Align-justify.svg","/assets/icons/duotone/Align-left.svg","/assets/icons/duotone/Align-right.svg","/assets/icons/duotone/Article.svg","/assets/icons/duotone/Bold.svg","/assets/icons/duotone/Bullet-list.svg","/assets/icons/duotone/Code.svg","/assets/icons/duotone/Dots.svg","/assets/icons/duotone/Edit-text.svg","/assets/icons/duotone/Filter.svg","/assets/icons/duotone/Font.svg","/assets/icons/duotone/H1.svg","/assets/icons/duotone/H2.svg","/assets/icons/duotone/Itallic.svg","/assets/icons/duotone/Menu.svg","/assets/icons/duotone/Paragraph.svg","/assets/icons/duotone/Quote1.svg","/assets/icons/duotone/Quote2.svg","/assets/icons/duotone/Redo.svg","/assets/icons/duotone/Strikethrough.svg","/assets/icons/duotone/Text-height.svg","/assets/icons/duotone/Text-width.svg","/assets/icons/duotone/Text.svg","/assets/icons/duotone/Toggle-Left.svg","/assets/icons/duotone/Toggle-Right.svg","/assets/icons/duotone/Toggle.svg","/assets/icons/duotone/Underline.svg","/assets/icons/duotone/Undo.svg"],"title":"SVG Duotone Text"},{"svgs":["/assets/icons/duotone/Angle Grinder.svg","/assets/icons/duotone/Axe.svg","/assets/icons/duotone/Brush.svg","/assets/icons/duotone/Compass.svg","/assets/icons/duotone/Hummer.svg","/assets/icons/duotone/Hummer2.svg","/assets/icons/duotone/Pantone.svg","/assets/icons/duotone/Road-Cone.svg","/assets/icons/duotone/Roller.svg","/assets/icons/duotone/Roulette.svg","/assets/icons/duotone/Screwdriver.svg","/assets/icons/duotone/Shovel.svg","/assets/icons/duotone/Spatula.svg","/assets/icons/duotone/Swiss-knife.svg","/assets/icons/duotone/Tools.svg"],"title":"SVG Duotone Tools"},{"svgs":["/assets/icons/duotone/Celcium.svg","/assets/icons/duotone/Cloud-fog.svg","/assets/icons/duotone/Cloud-sun.svg","/assets/icons/duotone/Cloud-wind.svg","/assets/icons/duotone/Cloud1.svg","/assets/icons/duotone/Cloud2.svg","/assets/icons/duotone/Cloudy-night.svg","/assets/icons/duotone/Cloudy.svg","/assets/icons/duotone/Day-rain.svg","/assets/icons/duotone/Fahrenheit.svg","/assets/icons/duotone/Fog.svg","/assets/icons/duotone/Moon.svg","/assets/icons/duotone/Night-fog.svg","/assets/icons/duotone/Night-rain.svg","/assets/icons/duotone/Rain1.svg","/assets/icons/duotone/Rain2.svg","/assets/icons/duotone/Rain5.svg","/assets/icons/duotone/Rainbow.svg","/assets/icons/duotone/Snow.svg","/assets/icons/duotone/Snow1.svg","/assets/icons/duotone/Snow2.svg","/assets/icons/duotone/Snow3.svg","/assets/icons/duotone/Storm.svg","/assets/icons/duotone/Sun-fog.svg","/assets/icons/duotone/Sun.svg","/assets/icons/duotone/Suset1.svg","/assets/icons/duotone/Suset2.svg","/assets/icons/duotone/Temperature-empty.svg","/assets/icons/duotone/Temperature-full.svg","/assets/icons/duotone/Temperature-half.svg","/assets/icons/duotone/Thunder-night.svg","/assets/icons/duotone/Thunder.svg","/assets/icons/duotone/Umbrella.svg","/assets/icons/duotone/Wind.svg"],"title":"SVG Duotone Weather"},
                {"svgs":["/assets/icons/duotune/abs001.svg","/assets/icons/duotune/abs002.svg","/assets/icons/duotune/abs003.svg","/assets/icons/duotune/abs004.svg","/assets/icons/duotune/abs005.svg","/assets/icons/duotune/abs006.svg","/assets/icons/duotune/abs007.svg","/assets/icons/duotune/abs008.svg","/assets/icons/duotune/abs009.svg","/assets/icons/duotune/abs010.svg","/assets/icons/duotune/abs011.svg","/assets/icons/duotune/abs012.svg","/assets/icons/duotune/abs013.svg","/assets/icons/duotune/abs014.svg","/assets/icons/duotune/abs015.svg","/assets/icons/duotune/abs016.svg","/assets/icons/duotune/abs017.svg","/assets/icons/duotune/abs018.svg","/assets/icons/duotune/abs019.svg","/assets/icons/duotune/abs020.svg","/assets/icons/duotune/abs021.svg","/assets/icons/duotune/abs022.svg","/assets/icons/duotune/abs023.svg","/assets/icons/duotune/abs024.svg","/assets/icons/duotune/abs025.svg","/assets/icons/duotune/abs026.svg","/assets/icons/duotune/abs027.svg","/assets/icons/duotune/abs028.svg","/assets/icons/duotune/abs029.svg","/assets/icons/duotune/abs030.svg","/assets/icons/duotune/abs031.svg","/assets/icons/duotune/abs032.svg","/assets/icons/duotune/abs033.svg","/assets/icons/duotune/abs034.svg","/assets/icons/duotune/abs035.svg","/assets/icons/duotune/abs036.svg","/assets/icons/duotune/abs037.svg","/assets/icons/duotune/abs038.svg","/assets/icons/duotune/abs039.svg","/assets/icons/duotune/abs040.svg","/assets/icons/duotune/abs041.svg","/assets/icons/duotune/abs042.svg","/assets/icons/duotune/abs043.svg","/assets/icons/duotune/abs044.svg","/assets/icons/duotune/abs045.svg","/assets/icons/duotune/abs046.svg","/assets/icons/duotune/abs047.svg","/assets/icons/duotune/abs048.svg","/assets/icons/duotune/abs049.svg","/assets/icons/duotune/abs050.svg","/assets/icons/duotune/abs051.svg","/assets/icons/duotune/abs052.svg"],"title":"SVG Duotune abstract"},{"svgs":["/assets/icons/duotune/arr001.svg","/assets/icons/duotune/arr002.svg","/assets/icons/duotune/arr003.svg","/assets/icons/duotune/arr004.svg","/assets/icons/duotune/arr005.svg","/assets/icons/duotune/arr006.svg","/assets/icons/duotune/arr007.svg","/assets/icons/duotune/arr008.svg","/assets/icons/duotune/arr009.svg","/assets/icons/duotune/arr010.svg","/assets/icons/duotune/arr011.svg","/assets/icons/duotune/arr012.svg","/assets/icons/duotune/arr013.svg","/assets/icons/duotune/arr014.svg","/assets/icons/duotune/arr015.svg","/assets/icons/duotune/arr016.svg","/assets/icons/duotune/arr017.svg","/assets/icons/duotune/arr018.svg","/assets/icons/duotune/arr019.svg","/assets/icons/duotune/arr020.svg","/assets/icons/duotune/arr021.svg","/assets/icons/duotune/arr022.svg","/assets/icons/duotune/arr023.svg","/assets/icons/duotune/arr024.svg","/assets/icons/duotune/arr025.svg","/assets/icons/duotune/arr026.svg","/assets/icons/duotune/arr027.svg","/assets/icons/duotune/arr028.svg","/assets/icons/duotune/arr029.svg","/assets/icons/duotune/arr030.svg","/assets/icons/duotune/arr031.svg","/assets/icons/duotune/arr032.svg","/assets/icons/duotune/arr033.svg","/assets/icons/duotune/arr034.svg","/assets/icons/duotune/arr035.svg","/assets/icons/duotune/arr036.svg","/assets/icons/duotune/arr037.svg","/assets/icons/duotune/arr038.svg","/assets/icons/duotune/arr039.svg","/assets/icons/duotune/arr040.svg","/assets/icons/duotune/arr041.svg","/assets/icons/duotune/arr042.svg","/assets/icons/duotune/arr043.svg","/assets/icons/duotune/arr044.svg","/assets/icons/duotune/arr045.svg","/assets/icons/duotune/arr046.svg","/assets/icons/duotune/arr047.svg","/assets/icons/duotune/arr048.svg","/assets/icons/duotune/arr049.svg","/assets/icons/duotune/arr050.svg","/assets/icons/duotune/arr051.svg","/assets/icons/duotune/arr052.svg","/assets/icons/duotune/arr053.svg","/assets/icons/duotune/arr054.svg","/assets/icons/duotune/arr055.svg","/assets/icons/duotune/arr056.svg","/assets/icons/duotune/arr057.svg","/assets/icons/duotune/arr058.svg","/assets/icons/duotune/arr059.svg","/assets/icons/duotune/arr060.svg","/assets/icons/duotune/arr061.svg","/assets/icons/duotune/arr062.svg","/assets/icons/duotune/arr063.svg","/assets/icons/duotune/arr064.svg","/assets/icons/duotune/arr065.svg","/assets/icons/duotune/arr066.svg","/assets/icons/duotune/arr067.svg","/assets/icons/duotune/arr068.svg","/assets/icons/duotune/arr069.svg","/assets/icons/duotune/arr070.svg","/assets/icons/duotune/arr071.svg","/assets/icons/duotune/arr072.svg","/assets/icons/duotune/arr073.svg","/assets/icons/duotune/arr074.svg","/assets/icons/duotune/arr075.svg","/assets/icons/duotune/arr076.svg","/assets/icons/duotune/arr077.svg","/assets/icons/duotune/arr078.svg","/assets/icons/duotune/arr079.svg","/assets/icons/duotune/arr080.svg","/assets/icons/duotune/arr081.svg","/assets/icons/duotune/arr082.svg","/assets/icons/duotune/arr084.svg","/assets/icons/duotune/arr085.svg","/assets/icons/duotune/arr086.svg","/assets/icons/duotune/arr087.svg","/assets/icons/duotune/arr088.svg","/assets/icons/duotune/arr089.svg","/assets/icons/duotune/arr090.svg","/assets/icons/duotune/arr091.svg","/assets/icons/duotune/arr092.svg"],"title":"SVG Duotune arrows"},{"svgs":["/assets/icons/duotune/art001.svg","/assets/icons/duotune/art002.svg","/assets/icons/duotune/art003.svg","/assets/icons/duotune/art004.svg","/assets/icons/duotune/art005.svg","/assets/icons/duotune/art006.svg","/assets/icons/duotune/art007.svg","/assets/icons/duotune/art008.svg","/assets/icons/duotune/art009.svg","/assets/icons/duotune/art010.svg"],"title":"SVG Duotune art"},{"svgs":["/assets/icons/duotune/cod001.svg","/assets/icons/duotune/cod002.svg","/assets/icons/duotune/cod003.svg","/assets/icons/duotune/cod004.svg","/assets/icons/duotune/cod005.svg","/assets/icons/duotune/cod006.svg","/assets/icons/duotune/cod007.svg","/assets/icons/duotune/cod008.svg","/assets/icons/duotune/cod009.svg","/assets/icons/duotune/cod010.svg"],"title":"SVG Duotune coding"},{"svgs":["/assets/icons/duotune/com001.svg","/assets/icons/duotune/com002.svg","/assets/icons/duotune/com003.svg","/assets/icons/duotune/com004.svg","/assets/icons/duotune/com005.svg","/assets/icons/duotune/com006.svg","/assets/icons/duotune/com007.svg","/assets/icons/duotune/com008.svg","/assets/icons/duotune/com009.svg","/assets/icons/duotune/com010.svg","/assets/icons/duotune/com011.svg","/assets/icons/duotune/com012.svg","/assets/icons/duotune/com013.svg","/assets/icons/duotune/com014.svg"],"title":"SVG Duotune communication"},{"svgs":["/assets/icons/duotune/ecm001.svg","/assets/icons/duotune/ecm002.svg","/assets/icons/duotune/ecm003.svg","/assets/icons/duotune/ecm004.svg","/assets/icons/duotune/ecm005.svg","/assets/icons/duotune/ecm006.svg","/assets/icons/duotune/ecm007.svg","/assets/icons/duotune/ecm008.svg","/assets/icons/duotune/ecm009.svg","/assets/icons/duotune/ecm010.svg","/assets/icons/duotune/ecm011.svg"],"title":"SVG Duotune ecommerce"},{"svgs":["/assets/icons/duotune/elc001.svg","/assets/icons/duotune/elc002.svg","/assets/icons/duotune/elc003.svg","/assets/icons/duotune/elc004.svg","/assets/icons/duotune/elc005.svg","/assets/icons/duotune/elc006.svg","/assets/icons/duotune/elc007.svg","/assets/icons/duotune/elc008.svg","/assets/icons/duotune/elc009.svg","/assets/icons/duotune/elc010.svg"],"title":"SVG Duotune electronics"},{"svgs":["/assets/icons/duotune/fil001.svg","/assets/icons/duotune/fil002.svg","/assets/icons/duotune/fil003.svg","/assets/icons/duotune/fil004.svg","/assets/icons/duotune/fil005.svg","/assets/icons/duotune/fil006.svg","/assets/icons/duotune/fil007.svg","/assets/icons/duotune/fil008.svg","/assets/icons/duotune/fil009.svg","/assets/icons/duotune/fil010.svg","/assets/icons/duotune/fil011.svg","/assets/icons/duotune/fil012.svg","/assets/icons/duotune/fil013.svg","/assets/icons/duotune/fil014.svg","/assets/icons/duotune/fil015.svg","/assets/icons/duotune/fil016.svg","/assets/icons/duotune/fil017.svg","/assets/icons/duotune/fil018.svg","/assets/icons/duotune/fil019.svg","/assets/icons/duotune/fil020.svg","/assets/icons/duotune/fil021.svg","/assets/icons/duotune/fil022.svg","/assets/icons/duotune/fil023.svg","/assets/icons/duotune/fil024.svg","/assets/icons/duotune/fil025.svg"],"title":"SVG Duotune files"},{"svgs":["/assets/icons/duotune/fin001.svg","/assets/icons/duotune/fin002.svg","/assets/icons/duotune/fin003.svg","/assets/icons/duotune/fin004.svg","/assets/icons/duotune/fin005.svg","/assets/icons/duotune/fin006.svg","/assets/icons/duotune/fin007.svg","/assets/icons/duotune/fin008.svg","/assets/icons/duotune/fin009.svg","/assets/icons/duotune/fin010.svg"],"title":"SVG Duotune finance"},{"svgs":["/assets/icons/duotune/gen001.svg","/assets/icons/duotune/gen002.svg","/assets/icons/duotune/gen003.svg","/assets/icons/duotune/gen004.svg","/assets/icons/duotune/gen005.svg","/assets/icons/duotune/gen006.svg","/assets/icons/duotune/gen007.svg","/assets/icons/duotune/gen008.svg","/assets/icons/duotune/gen009.svg","/assets/icons/duotune/gen010.svg","/assets/icons/duotune/gen011.svg","/assets/icons/duotune/gen012.svg","/assets/icons/duotune/gen013.svg","/assets/icons/duotune/gen014.svg","/assets/icons/duotune/gen015.svg","/assets/icons/duotune/gen016.svg","/assets/icons/duotune/gen017.svg","/assets/icons/duotune/gen018.svg","/assets/icons/duotune/gen019.svg","/assets/icons/duotune/gen020.svg","/assets/icons/duotune/gen021.svg","/assets/icons/duotune/gen022.svg","/assets/icons/duotune/gen023.svg","/assets/icons/duotune/gen024.svg","/assets/icons/duotune/gen025.svg","/assets/icons/duotune/gen026.svg","/assets/icons/duotune/gen027.svg","/assets/icons/duotune/gen028.svg","/assets/icons/duotune/gen029.svg","/assets/icons/duotune/gen030.svg","/assets/icons/duotune/gen031.svg","/assets/icons/duotune/gen032.svg","/assets/icons/duotune/gen033.svg","/assets/icons/duotune/gen034.svg","/assets/icons/duotune/gen035.svg","/assets/icons/duotune/gen036.svg","/assets/icons/duotune/gen037.svg","/assets/icons/duotune/gen038.svg","/assets/icons/duotune/gen039.svg","/assets/icons/duotune/gen040.svg","/assets/icons/duotune/gen041.svg","/assets/icons/duotune/gen042.svg","/assets/icons/duotune/gen043.svg","/assets/icons/duotune/gen044.svg","/assets/icons/duotune/gen045.svg","/assets/icons/duotune/gen046.svg","/assets/icons/duotune/gen047.svg","/assets/icons/duotune/gen048.svg","/assets/icons/duotune/gen049.svg","/assets/icons/duotune/gen050.svg","/assets/icons/duotune/gen051.svg","/assets/icons/duotune/gen052.svg","/assets/icons/duotune/gen053.svg","/assets/icons/duotune/gen054.svg","/assets/icons/duotune/gen055.svg","/assets/icons/duotune/gen056.svg","/assets/icons/duotune/gen057.svg","/assets/icons/duotune/gen058.svg","/assets/icons/duotune/gen059.svg","/assets/icons/duotune/gen060.svg","/assets/icons/duotune/gen061.svg"],"title":"SVG Duotune general"},{"svgs":["/assets/icons/duotune/gra001.svg","/assets/icons/duotune/gra002.svg","/assets/icons/duotune/gra003.svg","/assets/icons/duotune/gra004.svg","/assets/icons/duotune/gra005.svg","/assets/icons/duotune/gra006.svg","/assets/icons/duotune/gra007.svg","/assets/icons/duotune/gra008.svg","/assets/icons/duotune/gra009.svg","/assets/icons/duotune/gra010.svg","/assets/icons/duotune/gra011.svg","/assets/icons/duotune/gra012.svg"],"title":"SVG Duotune graphs"},{"svgs":["/assets/icons/duotune/lay001.svg","/assets/icons/duotune/lay002.svg","/assets/icons/duotune/lay003.svg","/assets/icons/duotune/lay004.svg","/assets/icons/duotune/lay005.svg","/assets/icons/duotune/lay006.svg","/assets/icons/duotune/lay007.svg","/assets/icons/duotune/lay008.svg","/assets/icons/duotune/lay009.svg","/assets/icons/duotune/lay010.svg"],"title":"SVG Duotune layouts"},{"svgs":["/assets/icons/duotune/map001.svg","/assets/icons/duotune/map002.svg","/assets/icons/duotune/map003.svg","/assets/icons/duotune/map004.svg","/assets/icons/duotune/map005.svg","/assets/icons/duotune/map006.svg","/assets/icons/duotune/map007.svg","/assets/icons/duotune/map008.svg","/assets/icons/duotune/map009.svg","/assets/icons/duotune/map010.svg"],"title":"SVG Duotune maps"},{"svgs":["/assets/icons/duotune/med001.svg","/assets/icons/duotune/med002.svg","/assets/icons/duotune/med003.svg","/assets/icons/duotune/med004.svg","/assets/icons/duotune/med005.svg","/assets/icons/duotune/med006.svg","/assets/icons/duotune/med007.svg","/assets/icons/duotune/med008.svg","/assets/icons/duotune/med009.svg","/assets/icons/duotune/med010.svg"],"title":"SVG Duotune medicine"},{"svgs":["/assets/icons/duotune/soc001.svg","/assets/icons/duotune/soc002.svg","/assets/icons/duotune/soc003.svg","/assets/icons/duotune/soc004.svg","/assets/icons/duotune/soc005.svg","/assets/icons/duotune/soc006.svg","/assets/icons/duotune/soc007.svg","/assets/icons/duotune/soc008.svg","/assets/icons/duotune/soc009.svg","/assets/icons/duotune/soc010.svg"],"title":"SVG Duotune social"},{"svgs":["/assets/icons/duotune/teh001.svg","/assets/icons/duotune/teh002.svg","/assets/icons/duotune/teh003.svg","/assets/icons/duotune/teh004.svg","/assets/icons/duotune/teh005.svg","/assets/icons/duotune/teh006.svg","/assets/icons/duotune/teh007.svg","/assets/icons/duotune/teh008.svg","/assets/icons/duotune/teh009.svg","/assets/icons/duotune/teh010.svg"],"title":"SVG Duotune technology"},{"svgs":["/assets/icons/duotune/txt001.svg","/assets/icons/duotune/txt002.svg","/assets/icons/duotune/txt003.svg","/assets/icons/duotune/txt004.svg","/assets/icons/duotune/txt005.svg","/assets/icons/duotune/txt006.svg","/assets/icons/duotune/txt007.svg","/assets/icons/duotune/txt008.svg","/assets/icons/duotune/txt009.svg","/assets/icons/duotune/txt010.svg"],"title":"SVG Duotune text"},
                {
                    "title": "Flat Icons",
                    "icons": [
                        "flaticon-users",
                        "flaticon-list-3",
                        "flaticon-file-1",
                        "flaticon-time-3",
                        "flaticon-profile-1",
                        "flaticon-time-2",
                        "flaticon-list-2",
                        "flaticon-multimedia-2",
                        "flaticon-interface-9",
                        "flaticon-file",
                        "flaticon-background",
                        "flaticon-chat-1",
                        "flaticon-graph",
                        "flaticon-pie-chart",
                        "flaticon-bag",
                        "flaticon-warning-2",
                        "flaticon-visible",
                        "flaticon-line-graph",
                        "flaticon-diagram",
                        "flaticon-statistics",
                        "flaticon-paper-plane",
                        "flaticon-cogwheel-2",
                        "flaticon-lifebuoy",
                        "flaticon-settings",
                        "flaticon-menu-button",
                        "flaticon-user",
                        "flaticon-apps",
                        "flaticon-clock-1",
                        "flaticon-close",
                        "flaticon-pin",
                        "flaticon-circle",
                        "flaticon-interface-8",
                        "flaticon-technology-1",
                        "flaticon-danger",
                        "flaticon-exclamation-square",
                        "flaticon-cancel",
                        "flaticon-calendar-2",
                        "flaticon-warning-sign",
                        "flaticon-more",
                        "flaticon-exclamation-2",
                        "flaticon-cogwheel-1",
                        "flaticon-book",
                        "flaticon-squares-4",
                        "flaticon-clock",
                        "flaticon-graphic-2",
                        "flaticon-symbol",
                        "flaticon-tool-1",
                        "flaticon-laptop",
                        "flaticon-event-calendar-symbol",
                        "flaticon-logout",
                        "flaticon-refresh",
                        "flaticon-questions-circular-button",
                        "flaticon-search-magnifier-interface-symbol",
                        "flaticon-search-1",
                        "flaticon-more-v2",
                        "flaticon-attachment",
                        "flaticon-speech-bubble-1",
                        "flaticon-open-box",
                        "flaticon-coins",
                        "flaticon-speech-bubble",
                        "flaticon-squares-3",
                        "flaticon-computer",
                        "flaticon-alert-2",
                        "flaticon-alert-off",
                        "flaticon-map",
                        "flaticon-interface-7",
                        "flaticon-graphic-1",
                        "flaticon-cogwheel",
                        "flaticon-alert-1",
                        "flaticon-folder-4",
                        "flaticon-interface-6",
                        "flaticon-interface-5",
                        "flaticon-calendar-1",
                        "flaticon-time-1",
                        "flaticon-signs-2",
                        "flaticon-calendar",
                        "flaticon-search",
                        "flaticon-infinity",
                        "flaticon-list-1",
                        "flaticon-bell",
                        "flaticon-delete",
                        "flaticon-squares-2",
                        "flaticon-clipboard",
                        "flaticon-shapes",
                        "flaticon-comment",
                        "flaticon-squares-1",
                        "flaticon-mark",
                        "flaticon-signs-1",
                        "flaticon-squares",
                        "flaticon-business",
                        "flaticon-car",
                        "flaticon-light",
                        "flaticon-information",
                        "flaticon-dashboard",
                        "flaticon-edit-1",
                        "flaticon-location",
                        "flaticon-technology",
                        "flaticon-exclamation-1",
                        "flaticon-tea-cup",
                        "flaticon-notes",
                        "flaticon-analytics",
                        "flaticon-transport",
                        "flaticon-truck",
                        "flaticon-user-settings",
                        "flaticon-user-add",
                        "flaticon-user-ok",
                        "flaticon-internet",
                        "flaticon-alert",
                        "flaticon-alarm",
                        "flaticon-grid-menu",
                        "flaticon-up-arrow-1",
                        "flaticon-more-v3",
                        "flaticon-lock-1",
                        "flaticon-profile",
                        "flaticon-map-location",
                        "flaticon-placeholder-2",
                        "flaticon-route",
                        "flaticon-more-v4",
                        "flaticon-lock",
                        "flaticon-multimedia-1",
                        "flaticon-add",
                        "flaticon-more-v5",
                        "flaticon-more-v6",
                        "flaticon-grid-menu-v2",
                        "flaticon-suitcase",
                        "flaticon-app",
                        "flaticon-interface-4",
                        "flaticon-time",
                        "flaticon-list",
                        "flaticon-music-2",
                        "flaticon-tool",
                        "flaticon-security",
                        "flaticon-interface-3",
                        "flaticon-interface-2",
                        "flaticon-interface-1",
                        "flaticon-layers",
                        "flaticon-placeholder-1",
                        "flaticon-placeholder",
                        "flaticon-web",
                        "flaticon-multimedia",
                        "flaticon-tabs",
                        "flaticon-signs",
                        "flaticon-interface",
                        "flaticon-network",
                        "flaticon-share",
                        "flaticon-info",
                        "flaticon-exclamation",
                        "flaticon-music-1",
                        "flaticon-medical",
                        "flaticon-imac",
                        "flaticon-cart",
                        "flaticon-download",
                        "flaticon-edit",
                        "flaticon-graphic",
                        "flaticon-browser",
                        "flaticon-up-arrow",
                        "flaticon-folder-3",
                        "flaticon-folder-2"
                    ]
                },
                {
                    "title": "TI | Arrows & Direction Icons",
                    "icons": [
                        "ti-arrow-up",
                        "ti-arrow-right",
                        "ti-arrow-left",
                        "ti-arrow-down",
                        "ti-arrows-vertical",
                        "ti-arrows-horizontal",
                        "ti-angle-up",
                        "ti-angle-right",
                        "ti-angle-left",
                        "ti-angle-down",
                        "ti-angle-double-up",
                        "ti-angle-double-right",
                        "ti-angle-double-left",
                        "ti-angle-double-down",
                        "ti-move",
                        "ti-fullscreen",
                        "ti-arrow-top-right",
                        "ti-arrow-top-left",
                        "ti-arrow-circle-up",
                        "ti-arrow-circle-right",
                        "ti-arrow-circle-left",
                        "ti-arrow-circle-down",
                        "ti-arrows-corner",
                        "ti-split-v",
                        "ti-split-v-alt",
                        "ti-split-h",
                        "ti-hand-point-up",
                        "ti-hand-point-right",
                        "ti-hand-point-left",
                        "ti-hand-point-down",
                        "ti-back-right",
                        "ti-back-left",
                        "ti-exchange-vertical"
                    ]
                },
                {
                    "title": "TI | Web App Icons",
                    "icons": [
                        "ti-wand",
                        "ti-save",
                        "ti-save-alt",
                        "ti-direction",
                        "ti-direction-alt",
                        "ti-user",
                        "ti-link",
                        "ti-unlink",
                        "ti-trash",
                        "ti-target",
                        "ti-tag",
                        "ti-desktop",
                        "ti-tablet",
                        "ti-mobile",
                        "ti-email",
                        "ti-star",
                        "ti-spray",
                        "ti-signal",
                        "ti-shopping-cart",
                        "ti-shopping-cart-full",
                        "ti-settings",
                        "ti-search",
                        "ti-zoom-in",
                        "ti-zoom-out",
                        "ti-cut",
                        "ti-ruler",
                        "ti-ruler-alt-2",
                        "ti-ruler-pencil",
                        "ti-ruler-alt",
                        "ti-bookmark",
                        "ti-bookmark-alt",
                        "ti-reload",
                        "ti-plus",
                        "ti-minus",
                        "ti-close",
                        "ti-pin",
                        "ti-pencil",
                        "ti-pencil-alt",
                        "ti-paint-roller",
                        "ti-paint-bucket",
                        "ti-na",
                        "ti-medall",
                        "ti-medall-alt",
                        "ti-marker",
                        "ti-marker-alt",
                        "ti-lock",
                        "ti-unlock",
                        "ti-location-arrow",
                        "ti-layout",
                        "ti-layers",
                        "ti-layers-alt",
                        "ti-key",
                        "ti-image",
                        "ti-heart",
                        "ti-heart-broken",
                        "ti-hand-stop",
                        "ti-hand-open",
                        "ti-hand-drag",
                        "ti-flag",
                        "ti-flag-alt",
                        "ti-flag-alt-2",
                        "ti-eye",
                        "ti-import",
                        "ti-export",
                        "ti-cup",
                        "ti-crown",
                        "ti-comments",
                        "ti-comment",
                        "ti-comment-alt",
                        "ti-thought",
                        "ti-clip",
                        "ti-check",
                        "ti-check-box",
                        "ti-camera",
                        "ti-announcement",
                        "ti-brush",
                        "ti-brush-alt",
                        "ti-palette",
                        "ti-briefcase",
                        "ti-bolt",
                        "ti-bolt-alt",
                        "ti-blackboard",
                        "ti-bag",
                        "ti-world",
                        "ti-wheelchair",
                        "ti-car",
                        "ti-truck",
                        "ti-timer",
                        "ti-ticket",
                        "ti-thumb-up",
                        "ti-thumb-down",
                        "ti-stats-up",
                        "ti-stats-down",
                        "ti-shine",
                        "ti-shift-right",
                        "ti-shift-left",
                        "ti-shift-right-alt",
                        "ti-shift-left-alt",
                        "ti-shield",
                        "ti-notepad",
                        "ti-server",
                        "ti-pulse",
                        "ti-printer",
                        "ti-power-off",
                        "ti-plug",
                        "ti-pie-chart",
                        "ti-panel",
                        "ti-package",
                        "ti-music",
                        "ti-music-alt",
                        "ti-mouse",
                        "ti-mouse-alt",
                        "ti-money",
                        "ti-microphone",
                        "ti-menu",
                        "ti-menu-alt",
                        "ti-map",
                        "ti-map-alt",
                        "ti-location-pin",
                        "ti-light-bulb",
                        "ti-info",
                        "ti-infinite",
                        "ti-id-badge",
                        "ti-hummer",
                        "ti-home",
                        "ti-help",
                        "ti-headphone",
                        "ti-harddrives",
                        "ti-harddrive",
                        "ti-gift",
                        "ti-game",
                        "ti-filter",
                        "ti-files",
                        "ti-file",
                        "ti-zip",
                        "ti-folder",
                        "ti-envelope",
                        "ti-dashboard",
                        "ti-cloud",
                        "ti-cloud-up",
                        "ti-cloud-down",
                        "ti-clipboard",
                        "ti-calendar",
                        "ti-book",
                        "ti-bell",
                        "ti-basketball",
                        "ti-bar-chart",
                        "ti-bar-chart-alt",
                        "ti-archive",
                        "ti-anchor",
                        "ti-alert",
                        "ti-alarm-clock",
                        "ti-agenda",
                        "ti-write",
                        "ti-wallet",
                        "ti-video-clapper",
                        "ti-video-camera",
                        "ti-vector",
                        "ti-support",
                        "ti-stamp",
                        "ti-slice",
                        "ti-shortcode",
                        "ti-receipt",
                        "ti-pin2",
                        "ti-pin-alt",
                        "ti-pencil-alt2",
                        "ti-eraser",
                        "ti-more",
                        "ti-more-alt",
                        "ti-microphone-alt",
                        "ti-magnet",
                        "ti-line-double",
                        "ti-line-dotted",
                        "ti-line-dashed",
                        "ti-ink-pen",
                        "ti-info-alt",
                        "ti-help-alt",
                        "ti-headphone-alt",
                        "ti-gallery",
                        "ti-face-smile",
                        "ti-face-sad",
                        "ti-credit-card",
                        "ti-comments-smiley",
                        "ti-time",
                        "ti-share",
                        "ti-share-alt",
                        "ti-rocket",
                        "ti-new-window",
                        "ti-rss",
                        "ti-rss-alt"
                    ]
                },
                {
                    "title": "TI | Control Icons",
                    "icons": [
                        "ti-control-stop",
                        "ti-control-shuffle",
                        "ti-control-play",
                        "ti-control-pause",
                        "ti-control-forward",
                        "ti-control-backward",
                        "ti-volume",
                        "ti-control-skip-forward",
                        "ti-control-skip-backward",
                        "ti-control-record",
                        "ti-control-eject"
                    ]
                },
                {
                    "title": "TI | Text Editor",
                    "icons": [
                        "ti-paragraph",
                        "ti-uppercase",
                        "ti-underline",
                        "ti-text",
                        "ti-Italic",
                        "ti-smallcap",
                        "ti-list",
                        "ti-list-ol",
                        "ti-align-right",
                        "ti-align-left",
                        "ti-align-justify",
                        "ti-align-center",
                        "ti-quote-right",
                        "ti-quote-left"
                    ]
                },
                {
                    "title": "TI | Layout Icons",
                    "icons": [
                        "ti-layout-width-full",
                        "ti-layout-width-default",
                        "ti-layout-width-default-alt",
                        "ti-layout-tab",
                        "ti-layout-tab-window",
                        "ti-layout-tab-v",
                        "ti-layout-tab-min",
                        "ti-layout-slider",
                        "ti-layout-slider-alt",
                        "ti-layout-sidebar-right",
                        "ti-layout-sidebar-none",
                        "ti-layout-sidebar-left",
                        "ti-layout-placeholder",
                        "ti-layout-menu",
                        "ti-layout-menu-v",
                        "ti-layout-menu-separated",
                        "ti-layout-menu-full",
                        "ti-layout-media-right",
                        "ti-layout-media-right-alt",
                        "ti-layout-media-overlay",
                        "ti-layout-media-overlay-alt",
                        "ti-layout-media-overlay-alt-2",
                        "ti-layout-media-left",
                        "ti-layout-media-left-alt",
                        "ti-layout-media-center",
                        "ti-layout-media-center-alt",
                        "ti-layout-list-thumb",
                        "ti-layout-list-thumb-alt",
                        "ti-layout-list-post",
                        "ti-layout-list-large-image",
                        "ti-layout-line-solid",
                        "ti-layout-grid4",
                        "ti-layout-grid3",
                        "ti-layout-grid2",
                        "ti-layout-grid2-thumb",
                        "ti-layout-cta-right",
                        "ti-layout-cta-left",
                        "ti-layout-cta-center",
                        "ti-layout-cta-btn-right",
                        "ti-layout-cta-btn-left",
                        "ti-layout-column4",
                        "ti-layout-column3",
                        "ti-layout-column2",
                        "ti-layout-accordion-separated",
                        "ti-layout-accordion-merged",
                        "ti-layout-accordion-list",
                        "ti-widgetized",
                        "ti-widget",
                        "ti-widget-alt",
                        "ti-view-list",
                        "ti-view-list-alt",
                        "ti-view-grid",
                        "ti-upload",
                        "ti-download",
                        "ti-loop",
                        "ti-layout-sidebar-2",
                        "ti-layout-grid4-alt",
                        "ti-layout-grid3-alt",
                        "ti-layout-grid2-alt",
                        "ti-layout-column4-alt",
                        "ti-layout-column3-alt",
                        "ti-layout-column2-alt"
                    ]
                },
                {
                    "title": "Brand Icons",
                    "icons": [
                        "ti-flickr",
                        "ti-flickr-alt",
                        "ti-instagram",
                        "ti-google",
                        "ti-github",
                        "ti-facebook",
                        "ti-dropbox",
                        "ti-dropbox-alt",
                        "ti-dribbble",
                        "ti-apple",
                        "ti-android",
                        "ti-yahoo",
                        "ti-trello",
                        "ti-stack-overflow",
                        "ti-soundcloud",
                        "ti-sharethis",
                        "ti-sharethis-alt",
                        "ti-reddit",
                        "ti-microsoft",
                        "ti-microsoft-alt",
                        "ti-linux",
                        "ti-jsfiddle",
                        "ti-joomla",
                        "ti-html5",
                        "ti-css3",
                        "ti-drupal",
                        "ti-wordpress",
                        "ti-tumblr",
                        "ti-tumblr-alt",
                        "ti-skype",
                        "ti-youtube",
                        "ti-vimeo",
                        "ti-vimeo-alt",
                        "ti-twitter",
                        "ti-twitter-alt",
                        "ti-linkedin",
                        "ti-pinterest",
                        "ti-pinterest-alt",
                        "ti-themify-logo",
                        "ti-themify-favicon",
                        "ti-themify-favicon-alt"
                    ]
                }
            ],
        }
    },
    methods:{
        setIcon(icon){
            this.$emit("setIcon", icon);
        }
    },
    computed: {
        lang() {
            const labels = ['search'];
            return labels.reduce((obj, key, i) => {
                obj[key] = this.$t('dataForm.' + labels[i]);
                return obj;
            }, {});
        },
        filteredIcons() {
            let iconGroup = [];

            if (this.iconSearch !== null && this.iconSearch != "") {
                this.iconData.forEach(group => {


                    if(group.hasOwnProperty("icons")){
                        let icons = group.icons.filter(icon => icon.includes(this.iconSearch.toLowerCase()));
                        if (icons.length >= 1) {
                            iconGroup.push({
                                title: group.title,
                                icons: icons
                            })
                        }
                    } else {
                        let svgs = group.svgs.filter(icon => icon.includes(this.iconSearch.toLowerCase()));
                        if (svgs.length >= 1) {
                            iconGroup.push({
                                title: group.title,
                                svgs: svgs
                            })
                        }
                    }

                });
            } else {
                return this.iconData
            }


            return iconGroup;
        },
    }
}
</script>

<style scoped>

</style>
